ALTER TABLE "SiteSetting" ADD COLUMN IF NOT EXISTS "mentoriaImageUrl" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SiteSetting" ADD COLUMN IF NOT EXISTS "credentialsImageUrl" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SiteSetting" ADD COLUMN IF NOT EXISTS "contactImageUrl" TEXT NOT NULL DEFAULT '';
